[package]
name    = "rft"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "FFT handling library."
repository  = "https://github.com/meh/rust-rft"
keywords    = ["audio", "fft"]

[features]
f32 = []
f64 = []

[dependencies]
num     = "*"
strided = "*"
